apiVersion: v1alpha1
kind: Setting
metadata:
  name: theme-terminal-setting
spec:
  forms:
    - group: basic
      label: 基本设置
      formSchema:
        - $formkit: text
          name: index_notice_title
          label: 首页公告标题
          value: 'Hello Halo!'
        - $formkit: textarea
          name: index_notice_content
          label: 首页公告内容
          value: '一款 Terminal 风格的 Halo 主题。'

